### ISSUE TITLE
extra mechs being assembled

### ISSUE THREAD

**Issue by gnivler** [Morphyum/AdjustedMechAssembly#8]
I'm going to test this further but I've been noticing it for a while I think, so wanted to mention it.

Example salvage at end of mission:
mech1 - you have 2/3
mech2 - you have 2/3
mech3 - you have 2/3
mech3
mech3

The result is two complete mech3 with 2/3 parts of mech1 2 and 3 remaining (none of the existing 2/3 pieces were consumed?)

The correct result I think should be 1 each of mech1, 2 and 3, with 0 parts leftover, except 2/3 for mech3.

Since I've been monkeying like the amateur I am with your code I'm going to start a new campaign without this mod loaded (but all the rest of what I use) and if it's OK, trying with your release, to isolate it as much as possible.

**Comment by gnivler** [comment]
Happening without this mod installed, not sure what is causing yet.  Closing bug report.

Specifically:  completed a Jenner, had 1/3 already.  Received 2 more, didn't get a Jenner and have 2/3 pieces left  o.O  Among other strangeness like receiving a Hawk even though I didn't salvage enough of one.

**Comment by gnivler** [comment]
I must have done testing wrong in my last comment, because this does seem to be isolated to this mod.  I think it might just be counting mech parts slightly off.  Going to try and patch it... wish me luck lol.

**Comment by Morphyum** [comment]
Gonna have a look if i have some time and you didn't find it till then ;-)

**Comment by gnivler** [comment]
I have muuuuch more confidence in you lol, but sounds great!  I hope I'm not wrong about the bug being real.

**Comment by gnivler** [comment]
I've made a BIT of progress... using your Logger to debug to file.

It appears something is doubling up the number of times the patch is being executed.  So I got 1 piece of Jenner, two pieces Locust (same variants obviously), and the patch logged two Jenner cycles and 4 Locust cycles.

My only guess is that this has something to do with reflection, but I know practically nothing about it.  Hopefully this info helps!

**Comment by gnivler** [comment]
This is a log output from getting 1 Jenner piece and 2 Locust pieces, when started with 2/3 and 0/3 respectively.  

Starting AddMechPart.Postfix with mechdef_locust_LCT-1M passed...
Insufficient parts for mechdef_locust_LCT-1M - currently 0 parts
Adding mechdef_locust_LCT-1M
We now have 1 of mechdef_locust_LCT-1M
Starting AddMechPart.Postfix with mechdef_locust_LCT-1M passed...
Insufficient parts for mechdef_locust_LCT-1M - currently 1 parts
Adding mechdef_locust_LCT-1M
We now have 2 of mechdef_locust_LCT-1M
Starting AddMechPart.Postfix with mechdef_jenner_JR7-D passed...
Insufficient parts for mechdef_jenner_JR7-D - currently 2 parts
Adding mechdef_jenner_JR7-D
We now have 3 of mechdef_jenner_JR7-D
Starting AddMechPart.Postfix with mechdef_jenner_JR7-D passed...
mechdef_jenner_JR7-D - We have enough of mechdef_jenner_JR7-D - 3 of 3
Mech instantiated - Jenner created
Adding mech mechdef_jenner_JR7-D to instance
Starting AddMechPart.Postfix with mechdef_locust_LCT-1M passed...
Insufficient parts for mechdef_locust_LCT-1M - currently 2 parts
Adding mechdef_locust_LCT-1M
We now have 3 of mechdef_locust_LCT-1M
Starting AddMechPart.Postfix with mechdef_locust_LCT-1M passed...
mechdef_locust_LCT-1M - We have enough of mechdef_locust_LCT-1M - 3 of 3
Mech instantiated - Locust created
Adding mech mechdef_locust_LCT-1M to instance

**Comment by gnivler** [comment]
I was able to confirm that pieces are being consumed just fine.

**Comment by gnivler** [comment]
I wonder if this might be a game bug.  I hooked up VS debugger without the mod loaded and it throws exceptions right at the point when AddMechPart is being called I suspect.

Exception thrown at 0x00000000410F996E in BattleTech.exe: 0xC0000005: Access violation reading location 0x0000000000000000. occurred

This is the disassembly [(https://pastebin.com/cGi1WbUG)]

If I drag the execution pointer to the next line in the disassembly and hit Continue I get a 2nd exception
Exception thrown at 0x00000000410FA66C in BattleTech.exe: 0xC0000005: Access violation reading location 0x0000000000000010. occurred

Not sure why the game is trying to access invalid memory locations.  Maybe benign wild goose chase.  Just offering observations cuz I'm clueless!

If I drag the execution pointer again and hit Continue the game resumes.

**Comment by gnivler** [comment]
It looks like it was indeed a game bug, in the beta branch.  Steam sent me a ~200-300MB patch (on experimental, now showing 1.0.4-2080D) and now this is working, and it's also fixed missing salvage at the end, from loading a combat save with existing salvage on the field.

This also explains why I thought it wasn't a bug, after opening the bug report, and then seeing it again - I changed branches on Steam.

Nothing to change to fix this but someone else should probably test it out...

**Comment by Morphyum** [comment]
watched a lot of streamers by now and didnt happen for them so closeing this
